sonar.verbose=true
sonar.organiszation=saidemy01-mykey
sonar.projectKey=saidemy01-mykey_saidemytrend
sonar.projectName=saidemytrend
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/class
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jcoco.xml
